# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4ff0305b2a3d517b42f5e9b5ba24672ea2d75101ae4afa50391328cf2c3c2e626e8c7afb1e2e648977b7f4bb93c786eaa243a2a52039607e69d6062e270cd1

test:
  secret_key_base: 7192e654a82c9d5a04d4366ad02cda1080fb26772c181125714d6a5f689ea4b64f089cfe7fab5310ccd035149f0880b33aaa5b2b0f261128a95b59e74a725e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
